[package]
name = "fatalii"
version = "0.1.2"
edition = "2018"

[dependencies]
engine = { path = "../engine" }
search = { path = "../search" }
uci = { path = "../uci" }

[dev-dependencies]
assert_matches = "1.5.0"
rexpect = "0.4.0"
