[package]
name = "fatalii"
version = "0.9.0"
edition = "2021"

[dependencies]
engine = { path = "../engine" }
eval = { path = "../eval" }
search = { path = "../search" }
uci = { path = "../uci" }

[dev-dependencies]
assert_matches = "1.5.0"
rexpect = "0.6.0"
