[package]
name = "movegen"
version = "0.1.0"
authors = ["Patrick Heck <49785565+FitzOReilly@users.noreply.github.com>"]
edition = "2024"

[dependencies]
bitflags = "2.11.0"
smallvec = "1.15.1"
thiserror = "2.0.18"

[dev-dependencies]
criterion = "0.8.2"
rand = "0.10"

[[bench]]
name = "bench_movegen"
harness = false
