name: Coverage

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cargo install cargo-tarpaulin
    - name: Build
      run: cargo build --verbose
    - name: Generate code coverage
      run: |
        cargo tarpaulin --verbose --timeout 120 --out Xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
